// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs-04kUJrRuIlwIR02EqCBlfwmoU2lhCU',
    appId: '1:1045227405419:web:38943a1bead60584e2b12e',
    messagingSenderId: '1045227405419',
    projectId: 'offline-first-28569',
    authDomain: 'offline-first-28569.firebaseapp.com',
    storageBucket: 'offline-first-28569.firebasestorage.app',
    measurementId: 'G-YCWH5C5R68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMR8bkrxTv0UQQ3yZWg5xhf0cIilZlsjE',
    appId: '1:1045227405419:android:90fa1696636441e3e2b12e',
    messagingSenderId: '1045227405419',
    projectId: 'offline-first-28569',
    storageBucket: 'offline-first-28569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPvxScv2I69fyAr3vNlj4Nvr1OFUXIIQ4',
    appId: '1:1045227405419:ios:a15288260c1f4fc2e2b12e',
    messagingSenderId: '1045227405419',
    projectId: 'offline-first-28569',
    storageBucket: 'offline-first-28569.firebasestorage.app',
    iosBundleId: 'app.b4a.mangatrix.testeOfflineFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPvxScv2I69fyAr3vNlj4Nvr1OFUXIIQ4',
    appId: '1:1045227405419:ios:a15288260c1f4fc2e2b12e',
    messagingSenderId: '1045227405419',
    projectId: 'offline-first-28569',
    storageBucket: 'offline-first-28569.firebasestorage.app',
    iosBundleId: 'app.b4a.mangatrix.testeOfflineFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs-04kUJrRuIlwIR02EqCBlfwmoU2lhCU',
    appId: '1:1045227405419:web:0f91de65300a2829e2b12e',
    messagingSenderId: '1045227405419',
    projectId: 'offline-first-28569',
    authDomain: 'offline-first-28569.firebaseapp.com',
    storageBucket: 'offline-first-28569.firebasestorage.app',
    measurementId: 'G-59Y6LJ4HRX',
  );
}
